# .github/workflows/gradle-build-pr.yml
name: Run Build on PRs
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        task: [first]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    # run the build
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
    # upload build output for later inspection, always
    #  N.B only applies to the last task in the matrix
    - uses: actions/upload-artifact@v2
      with:
        name: advancedplayappbuild
        path: build